### PR TITLE
update metadata and safetyGraphics example to use mg/dL for creatinine

### LINKED ISSUE #135: Consider Units/log scale when data is provided that has larger range
with safetydata it is currently stretching the chart. is that due to units or range? we should check and see what values for creatinine are medically possible. Can add log scale if this varies widely, otherwise need to make assumptions clear about units

### PR DESCRIPTION
**Pull request by pburnsdata**
### Issues
closes #135

Jim mentioned that 10 was probably the highest we'd ever need to account for

### CODE REVIEW

**Comment by Lovemore-Gakava** [comment]
@pburnsdata all looks good.

**Comment by jwoolfolk** [comment]
@pburnsdata - this looks good and happy to close to , but one concern I did have was if we wanted to convert to a non CDISC standard units or if we wanted to present in standard units and have the scale of the chart altered instead? I hope this makes sense.

**Review by Lovemore-Gakava — APPROVED** [review]

**Comment by pburnsdata** [comment]
@jwoolfolk it makes sense - I had sort of a similar thought about supporting SI units. Our cut offs for the the delta creatinine changes are set up in conventional units right now but I feel like supporting SI units could be nice. Converting the cut offs to SI of course isn't as pretty (e.g. like instead of 1.5 mg/dL being the cut off for stage 2 it'll be 132.63 umol/L in SI) I'll be out on leave for the next two weeks but if y'all have one of the renal meetings with Jim maybe ask him about it - I wonder if there's a reason he left this in conventional units and if he thinks supporting SI is useful/how useful.

If we do support both Conv and SI then we'll need to think about how to pass that in to the chart as a mapping potentially...

Alternatively we could completely switch over to SI but again I wonder if there's a reason Jim had this in conventional besides the clean cut offs (I'm guessing the literature does this?)

**Comment by pburnsdata** [comment]
Jim confirmed that we will be only supporting CONV units for now

**Pull request merged**
